language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
#  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.1"
  - travis_retry composer update --dev --prefer-dist --no-interaction
# setup application:
  - |
    sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" config/web.php
before_script:
      - mysql -uroot -p265463 -h 127.0.0.1 -e 'create database IF NOT EXISTS baseportal character set utf8 collate utf8_general_ci;'
script:
  - |
    php -S localhost:8080 -t web > /dev/null 2>&1 &
    composer exec codecept run acceptance
services:
      - mysql
notifications:
  slack:
    on_success: never
    on_failure: never
addons:
  sauce_connect:
    username: "vovanchoRus"
    access_key: "73875a55-4ac8-4534-bfe5-93e5e308250b"